/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Include CMSIS first */
/* Define MCU */

#define GPIOA_CLK_EN	(1<<0)
#define GPIOG_CLK_EN	(1<<6)

#define LED1_MODER		(1<<26)
#define LED2_MODER		(1<<28)

#define BTN_POS			0
#define LED1_POS		13
#define LED2_POS		14

void delay();

int main(void)
{
	/* Enable clock for port A and G */
	RCC->AHB1ENR |= (GPIOA_CLK_EN | GPIOG_CLK_EN);

	/* Configure button as input - zero both bits in MODER register */
	GPIOA->MODER &= ~(1<<BTN_POS);
	GPIOA->MODER &= ~(1<<(BTN_POS+1));

	/* Configure led pins as outputs */
	GPIOG->MODER |= LED1_MODER | LED2_MODER;

    /* Loop forever */
	for(;;)
	{
		/* Set all leds */
		GPIOG->BSRR = ((1<<LED1_POS) | (1<<LED2_POS));

		delay();

		/* Unset led 1*/
		GPIOG->BSRR = (1<<(LED1_POS + 16));

		delay();

		/* Unset led 2*/
		GPIOG->BSRR = (1<<(LED2_POS + 16));

		delay();
	}
}

void delay()
{
	uint32_t top;

	/* Check if button is pressed - high is active state */
	if(GPIOA->IDR & (1<<BTN_POS))
		top = 80000;
	else
		top = 320000;

	/* Dummy loop for delay */
	for(int i=0; i<top; i++);
}
