/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Include CMSIS first */
/* Define MCU */

#define GPIOG_CLK_EN	(1<<6)

#define LED1_MODER		(1<<26)
#define LED2_MODER		(1<<28)

#define LED1_POS		13
#define LED2_POS		14

int main(void)
{
	/* Enable clock for port G */
	RCC->AHB1ENR |= GPIOG_CLK_EN;

	/* Configure led pins as outputs */
	GPIOG->MODER |= LED1_MODER | LED2_MODER;

    /* Loop forever */
	for(;;)
	{
		/* Set all leds */
		GPIOG->BSRR = ((1<<LED1_POS) | (1<<LED2_POS));

		/* Dummy loop for delay */
		for(int i=0; i<160000; i++);

		/* Unset led 1*/
		GPIOG->BSRR = (1<<(LED1_POS + 16));

		/* Dummy loop for delay */
		for(int i=0; i<320000; i++);

		/* Unset led 2*/
		GPIOG->BSRR = (1<<(LED2_POS + 16));

		/* Dummy loop for delay */
		for(int i=0; i<160000; i++);
	}
}
