/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>
#include "uart.h"
#include "led.h"
#include "adc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Include CMSIS first */
/* Define MCU */

void delay();

volatile int sensor_value;

void ADC_IRQHandler()
{
	/* Check if end-of-conversion interrupt */
	if(ADC1->SR & ADC_SR_EOC)
	{
		/* Clear EOC flag */
		CLEAR_BIT(ADC1->SR, ADC_SR_EOC);

		/* Do something */
		sensor_value = ADC1->DR;
	}
}

int main(void)
{
	usart1_rxtx_init();
	adc1_interrupt_init();

	printf("Program start\n");

    /* Loop forever */
	for(;;)
	{
		printf("Sensor value is %d\n", sensor_value);
		delay();
	}
}

void delay()
{
	/* Dummy loop for delay */
	for(int i=0; i<80000; i++);
}
