/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Include CMSIS first */
/* Define MCU */

void delay();

int main(void)
{
	usart1_rxtx_init();
	user_led_init();
	uint8_t ch;

	printf("Program start\n");

    /* Loop forever */
	for(;;)
	{
		ch = uart_read(USART1);

		switch(ch)
		{
		case '1':
			led_toggle(LED1);
			break;
		case '2':
			led_toggle(LED2);
			break;
		case 'n':
			led_on(LED1);
			led_on(LED2);
			break;
		case 'f':
			led_off(LED1);
			led_off(LED2);
			break;
		default:
			printf("Received char. \'%c\'\n", ch);
		}
	}
}

void delay()
{
	/* Dummy loop for delay */
	for(int i=0; i<320000; i++);
}
