/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Include CMSIS first */
/* Define MCU */

void delay();

void USART1_IRQHandler()
{
	/* Check TXE flag */
	if(USART1->SR & USART_SR_TXE)
	{
		/* Clear TXE flag by write to DR register */
		USART1->DR = '.';
	}
}

int main(void)
{
	usart1_tx_interrupt_init();
	user_led_init();

    /* Loop forever */
	for(;;)
	{
		led_toggle(LED1);
		delay();
	}
}

void delay()
{
	/* Dummy loop for delay */
	for(int i=0; i<320000; i++);
}
